/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicSplatRouteImport } from './routes/_public/$'
import { Route as ProtectedDashboardIndexRouteImport } from './routes/_protected/dashboard/index'
import { Route as ProtectedDashboardSplatRouteImport } from './routes/_protected/dashboard/$'
import { Route as ProtectedDashboardPenjualanIndexRouteImport } from './routes/_protected/dashboard/penjualan/index'
import { Route as ProtectedDashboardMasterUsersIndexRouteImport } from './routes/_protected/dashboard/master/users/index'
import { Route as ProtectedDashboardMasterTipePenjualanIndexRouteImport } from './routes/_protected/dashboard/master/tipe-penjualan/index'
import { Route as ProtectedDashboardMasterPembayaranIndexRouteImport } from './routes/_protected/dashboard/master/pembayaran/index'
import { Route as ProtectedDashboardMasterItemsIndexRouteImport } from './routes/_protected/dashboard/master/items/index'
import { Route as ProtectedDashboardMasterCabangIndexRouteImport } from './routes/_protected/dashboard/master/cabang/index'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicSplatRoute = PublicSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => PublicRouteRoute,
} as any)
const ProtectedDashboardIndexRoute = ProtectedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedDashboardSplatRoute = ProtectedDashboardSplatRouteImport.update({
  id: '/dashboard/$',
  path: '/dashboard/$',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedDashboardPenjualanIndexRoute =
  ProtectedDashboardPenjualanIndexRouteImport.update({
    id: '/dashboard/penjualan/',
    path: '/dashboard/penjualan/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedDashboardMasterUsersIndexRoute =
  ProtectedDashboardMasterUsersIndexRouteImport.update({
    id: '/dashboard/master/users/',
    path: '/dashboard/master/users/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedDashboardMasterTipePenjualanIndexRoute =
  ProtectedDashboardMasterTipePenjualanIndexRouteImport.update({
    id: '/dashboard/master/tipe-penjualan/',
    path: '/dashboard/master/tipe-penjualan/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedDashboardMasterPembayaranIndexRoute =
  ProtectedDashboardMasterPembayaranIndexRouteImport.update({
    id: '/dashboard/master/pembayaran/',
    path: '/dashboard/master/pembayaran/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedDashboardMasterItemsIndexRoute =
  ProtectedDashboardMasterItemsIndexRouteImport.update({
    id: '/dashboard/master/items/',
    path: '/dashboard/master/items/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedDashboardMasterCabangIndexRoute =
  ProtectedDashboardMasterCabangIndexRouteImport.update({
    id: '/dashboard/master/cabang/',
    path: '/dashboard/master/cabang/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$': typeof PublicSplatRoute
  '/': typeof PublicIndexRoute
  '/dashboard/$': typeof ProtectedDashboardSplatRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/dashboard/penjualan': typeof ProtectedDashboardPenjualanIndexRoute
  '/dashboard/master/cabang': typeof ProtectedDashboardMasterCabangIndexRoute
  '/dashboard/master/items': typeof ProtectedDashboardMasterItemsIndexRoute
  '/dashboard/master/pembayaran': typeof ProtectedDashboardMasterPembayaranIndexRoute
  '/dashboard/master/tipe-penjualan': typeof ProtectedDashboardMasterTipePenjualanIndexRoute
  '/dashboard/master/users': typeof ProtectedDashboardMasterUsersIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof PublicSplatRoute
  '/': typeof PublicIndexRoute
  '/dashboard/$': typeof ProtectedDashboardSplatRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/dashboard/penjualan': typeof ProtectedDashboardPenjualanIndexRoute
  '/dashboard/master/cabang': typeof ProtectedDashboardMasterCabangIndexRoute
  '/dashboard/master/items': typeof ProtectedDashboardMasterItemsIndexRoute
  '/dashboard/master/pembayaran': typeof ProtectedDashboardMasterPembayaranIndexRoute
  '/dashboard/master/tipe-penjualan': typeof ProtectedDashboardMasterTipePenjualanIndexRoute
  '/dashboard/master/users': typeof ProtectedDashboardMasterUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_public/$': typeof PublicSplatRoute
  '/_public/': typeof PublicIndexRoute
  '/_protected/dashboard/$': typeof ProtectedDashboardSplatRoute
  '/_protected/dashboard/': typeof ProtectedDashboardIndexRoute
  '/_protected/dashboard/penjualan/': typeof ProtectedDashboardPenjualanIndexRoute
  '/_protected/dashboard/master/cabang/': typeof ProtectedDashboardMasterCabangIndexRoute
  '/_protected/dashboard/master/items/': typeof ProtectedDashboardMasterItemsIndexRoute
  '/_protected/dashboard/master/pembayaran/': typeof ProtectedDashboardMasterPembayaranIndexRoute
  '/_protected/dashboard/master/tipe-penjualan/': typeof ProtectedDashboardMasterTipePenjualanIndexRoute
  '/_protected/dashboard/master/users/': typeof ProtectedDashboardMasterUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/'
    | '/dashboard/$'
    | '/dashboard'
    | '/dashboard/penjualan'
    | '/dashboard/master/cabang'
    | '/dashboard/master/items'
    | '/dashboard/master/pembayaran'
    | '/dashboard/master/tipe-penjualan'
    | '/dashboard/master/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/'
    | '/dashboard/$'
    | '/dashboard'
    | '/dashboard/penjualan'
    | '/dashboard/master/cabang'
    | '/dashboard/master/items'
    | '/dashboard/master/pembayaran'
    | '/dashboard/master/tipe-penjualan'
    | '/dashboard/master/users'
  id:
    | '__root__'
    | '/_protected'
    | '/_public'
    | '/_public/$'
    | '/_public/'
    | '/_protected/dashboard/$'
    | '/_protected/dashboard/'
    | '/_protected/dashboard/penjualan/'
    | '/_protected/dashboard/master/cabang/'
    | '/_protected/dashboard/master/items/'
    | '/_protected/dashboard/master/pembayaran/'
    | '/_protected/dashboard/master/tipe-penjualan/'
    | '/_protected/dashboard/master/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/$': {
      id: '/_public/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof PublicSplatRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/dashboard/$': {
      id: '/_protected/dashboard/$'
      path: '/dashboard/$'
      fullPath: '/dashboard/$'
      preLoaderRoute: typeof ProtectedDashboardSplatRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/dashboard/penjualan/': {
      id: '/_protected/dashboard/penjualan/'
      path: '/dashboard/penjualan'
      fullPath: '/dashboard/penjualan'
      preLoaderRoute: typeof ProtectedDashboardPenjualanIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/dashboard/master/users/': {
      id: '/_protected/dashboard/master/users/'
      path: '/dashboard/master/users'
      fullPath: '/dashboard/master/users'
      preLoaderRoute: typeof ProtectedDashboardMasterUsersIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/dashboard/master/tipe-penjualan/': {
      id: '/_protected/dashboard/master/tipe-penjualan/'
      path: '/dashboard/master/tipe-penjualan'
      fullPath: '/dashboard/master/tipe-penjualan'
      preLoaderRoute: typeof ProtectedDashboardMasterTipePenjualanIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/dashboard/master/pembayaran/': {
      id: '/_protected/dashboard/master/pembayaran/'
      path: '/dashboard/master/pembayaran'
      fullPath: '/dashboard/master/pembayaran'
      preLoaderRoute: typeof ProtectedDashboardMasterPembayaranIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/dashboard/master/items/': {
      id: '/_protected/dashboard/master/items/'
      path: '/dashboard/master/items'
      fullPath: '/dashboard/master/items'
      preLoaderRoute: typeof ProtectedDashboardMasterItemsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/dashboard/master/cabang/': {
      id: '/_protected/dashboard/master/cabang/'
      path: '/dashboard/master/cabang'
      fullPath: '/dashboard/master/cabang'
      preLoaderRoute: typeof ProtectedDashboardMasterCabangIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedDashboardSplatRoute: typeof ProtectedDashboardSplatRoute
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
  ProtectedDashboardPenjualanIndexRoute: typeof ProtectedDashboardPenjualanIndexRoute
  ProtectedDashboardMasterCabangIndexRoute: typeof ProtectedDashboardMasterCabangIndexRoute
  ProtectedDashboardMasterItemsIndexRoute: typeof ProtectedDashboardMasterItemsIndexRoute
  ProtectedDashboardMasterPembayaranIndexRoute: typeof ProtectedDashboardMasterPembayaranIndexRoute
  ProtectedDashboardMasterTipePenjualanIndexRoute: typeof ProtectedDashboardMasterTipePenjualanIndexRoute
  ProtectedDashboardMasterUsersIndexRoute: typeof ProtectedDashboardMasterUsersIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedDashboardSplatRoute: ProtectedDashboardSplatRoute,
  ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
  ProtectedDashboardPenjualanIndexRoute: ProtectedDashboardPenjualanIndexRoute,
  ProtectedDashboardMasterCabangIndexRoute:
    ProtectedDashboardMasterCabangIndexRoute,
  ProtectedDashboardMasterItemsIndexRoute:
    ProtectedDashboardMasterItemsIndexRoute,
  ProtectedDashboardMasterPembayaranIndexRoute:
    ProtectedDashboardMasterPembayaranIndexRoute,
  ProtectedDashboardMasterTipePenjualanIndexRoute:
    ProtectedDashboardMasterTipePenjualanIndexRoute,
  ProtectedDashboardMasterUsersIndexRoute:
    ProtectedDashboardMasterUsersIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicSplatRoute: typeof PublicSplatRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicSplatRoute: PublicSplatRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
